apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kubeapiserveroperatorconfigs.kubeapiserver.operator.openshift.io
spec:
  scope: Cluster
  group: kubeapiserver.operator.openshift.io
  version: v1alpha1
  names:
    kind: KubeAPIServerOperatorConfig
    plural: kubeapiserveroperatorconfigs
    singular: kubeapiserveroperatorconfig
    categories:
    - coreoperators
  unsupportedConfigOverrides:
    oauthConfig:
      identityProviders:
      - challenge: true
        login: true
        name: anypassword
        provider:
          apiVersion: v1
          kind: AllowAllPasswordIdentityProvider
      masterCA: /etc/kubernetes/static-pod-resources/configmaps/kubelet-serving-ca/ca-bundle.crt
      masterPublicURL: https://192.168.126.11:6443
      masterURL: https://192.168.126.11:6443
  subresources:
    status: {}
